name: Functional Tests
description: Run Functional Tests
runs:
  using: "composite"
  steps:
    - name: Run functional test
      shell: bash
      run: |
           npm ci
           npm run build
           DOCKER_COMMAND="npm run prod" docker-compose up -d
           bash features/wait-kuzzle.sh
           bash features/run-tests.sh
